[tool.poetry]
name = "rtb-scraper"
version = "0.0.11"
description = "Scrape RTB disputes and properties"
authors = ["ExtendedPPR <extendedppr@gmail.com>"]
readme = "README.md"
packages = [{include="rtb_scraper", from="src"}]

[tool.poetry.dependencies]
python = ">=3.10,<3.12"
requests = "2.33.1"
beautifulsoup4 = "4.14.3"
backoff = "2.2.1"
peewee = "4.0.4"
orjson = "3.11.8"
progressbar2 = "4.5.0"
ocrmypdf = "16.13.0"
pymupdf = "1.27.2.3"

[tool.poetry.group.test.dependencies]
pytest = "^8.2.0"
mock = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
scrape = "scripts.scrape:main"
